apiVersion: cluster.kurator.dev/v1alpha1
kind: AttachedCluster
metadata:
  name: kurator-member1
  namespace: default
spec:
  kubeconfig:
    name: kurator-member1
    key: kurator-member1.config
---
apiVersion: cluster.kurator.dev/v1alpha1
kind: AttachedCluster
metadata:
  name: kurator-member2
  namespace: default
spec:
  kubeconfig:
    name: kurator-member2
    key: kurator-member2.config
---
apiVersion: fleet.kurator.dev/v1alpha1
kind: Fleet
metadata:
  name: quickstart
  namespace: default
spec:
  clusters:
    - name: kurator-member1
      kind: AttachedCluster
    - name: kurator-member2
      kind: AttachedCluster
  plugin:
    submariner:
      brokerCluster: kurator-member1
      clusterCidrs:
        kurator-member1: 10.10.0.0/24
        kurator-member2: 10.12.0.0/24
      serviceCidrs:
        kurator-member1: 10.96.0.0/16
        kurator-member2: 10.96.0.0/16
      globalcidrs:
        kurator-member1: 242.1.0.0/16
        kurator-member2: 242.2.0.0/16
      extraArgs:
        ipsec:
          psk: $SUBMARINER_PSK
